repos:
  - hooks:
      - id: ruff
        name: ruff
    repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282

  - hooks:
      - id: black
        args:
          - "--check"
    rev: 23.7.0
    repo: https://github.com/psf/black

  - hooks:
      - id: pyright
        entry: pyright
        pass_filenames: false
        types: [python]
        args:
          - "--pythonpath=.venv/bin/python"
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.316
