name: lint & test

on:
  push:
    branches: [dev]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
  pull_request:
    branches: [dev, main]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install rye
        uses: phi-friday/install-rye@v1.4
        id: install-rye
        with:
          python_version: ${{ matrix.python-version }}
          use_uv: true

      - name: Load cached venv
        id: cached-venv-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.install-rye.outputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        if: steps.cached-venv-dependencies.outputs.cache-hit != 'true'
        run: |
          rye sync --all-features

      - name: Load cached pre-commit
        id: cached-pre-commit-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: venv-${{ runner.os }}-${{ steps.install-rye.outputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Code checks
        run: |
          rye run pre-commit run --all-files --show-diff-on-failure

      - name: Test with pytest
        run: |
          rye run pytest
